import { Department } from '@/types';

export const DEPARTMENTS: Department[] = [
  {
    id: 'construcao-basica',
    slug: 'construcao-basica',
    name: 'Construção Básica',
    description: 'Cimento, cal, areia, brita, tijolos, vigas de ferro, treliças e telhas.',
    iconName: 'Building2',
    color: 'from-amber-600 to-amber-800',
    image: '/images/produtos/cimento-itau-todas-as-obras-50kg-votoran.webp',
  },
  {
    id: 'pisos-e-revestimentos',
    slug: 'pisos-e-revestimentos',
    name: 'Pisos e Revestimentos',
    description: 'Pisos cerâmicos, porcelanatos, argamassas colantes, rejuntes e niveladores.',
    iconName: 'Sparkles',
    color: 'from-cyan-600 to-teal-800',
    image: '/images/produtos/piso-palau-brilhante-61x61-ceral.webp',
  },
  {
    id: 'quimicos-e-adesivos',
    slug: 'quimicos-e-adesivos',
    name: 'Impermeabilizantes e Químicos',
    description: 'Vedacit, Bianco, selantes PU 40, Fixa Tudo, silicones, espumas e colas.',
    iconName: 'Droplets',
    color: 'from-blue-600 to-blue-800',
    image: '/images/produtos/aditivo-impermeabilizante-vedacit.webp',
  },
  {
    id: 'pintura',
    slug: 'pintura',
    name: 'Pintura e Acessórios',
    description: 'Tintas látex, tintas spray, solventes, thinners, trinchas, rolos e fitas.',
    iconName: 'Paintbrush',
    color: 'from-orange-500 to-red-600',
    image: '/images/produtos/tinta-latex-renove-3-6l.webp',
  },
  {
    id: 'hidraulica',
    slug: 'hidraulica',
    name: 'Tubos e Conexões',
    description: 'Tubos e conexões soldáveis, registros, caixas Sabesp, sifões e ralos.',
    iconName: 'Droplets',
    color: 'from-sky-600 to-blue-700',
    image: '/images/produtos/joelho-90-soldavel-25mm-amanco.webp',
  },
  {
    id: 'eletrica',
    slug: 'eletrica',
    name: 'Elétrica e Iluminação',
    description: 'Fios e cabos flexíveis, tomadas, interruptores, módulos e lâmpadas LED.',
    iconName: 'Zap',
    color: 'from-yellow-500 to-amber-600',
    image: '/images/produtos/cabo-flexivel-2-5mm-750v-100m-sil-azul.webp',
  },
  {
    id: 'banheiro-e-cozinha',
    slug: 'banheiro-e-cozinha',
    name: 'Banheiro e Cozinha',
    description: 'Bacias sanitárias, assentos, gabinetes, pias de granito, torneiras e chuveiros.',
    iconName: 'Sparkles',
    color: 'from-emerald-600 to-teal-800',
    image: '/images/produtos/bacia-sanitaria-convencional-deca-izy.webp',
  },
  {
    id: 'ferramentas',
    slug: 'ferramentas',
    name: 'Ferramentas e Equipamentos',
    description: 'Pás, carriolas, trenas, discos de corte, chaves combinadas e aplicadores.',
    iconName: 'Hammer',
    color: 'from-slate-600 to-slate-800',
    image: '/images/produtos/pa-de-bico-tramontina.webp',
  },
  {
    id: 'ferragens',
    slug: 'ferragens',
    name: 'Ferragens e Segurança',
    description: 'Fechaduras, dobradiças, pregos com cabeça, mãos francesas e parafusos.',
    iconName: 'Wrench',
    color: 'from-zinc-600 to-zinc-800',
    image: '/images/produtos/fechadura-banheiro-stam-1820-21.webp',
  },
  {
    id: 'jardim-e-utilidades',
    slug: 'jardim-e-utilidades',
    name: 'Jardim e Área Externa',
    description: 'Mangueiras de jardim trançadas, esguichos, desengripantes e lubrificantes.',
    iconName: 'Wrench',
    color: 'from-green-600 to-emerald-800',
    image: '/images/produtos/mangueira-jardim-durin-trancada-1-2.webp',
  },
];
