import { Department } from '@/types';

export const DEPARTMENTS: Department[] = [
  {
    id: 'construcao-basica',
    slug: 'construcao-basica',
    name: 'Construção Básica',
    navName: 'Construção Básica',
    description: 'Cimento, cal, areia, brita, tijolos, vigas de ferro, treliças e telhas.',
    iconName: 'Building2',
    color: 'from-amber-600 to-amber-900',
    image: '/images/departamentos/construcao-basica.webp',
  },
  {
    id: 'pisos-e-revestimentos',
    slug: 'pisos-e-revestimentos',
    name: 'Pisos e Revestimentos',
    navName: 'Pisos',
    description: 'Pisos cerâmicos, porcelanatos, argamassas colantes, rejuntes e niveladores.',
    iconName: 'Sparkles',
    color: 'from-cyan-700 to-slate-900',
    image: '/images/departamentos/pisos-e-revestimentos.webp',
  },
  {
    id: 'quimicos-e-adesivos',
    slug: 'quimicos-e-adesivos',
    name: 'Impermeabilizantes e Químicos',
    navName: 'Impermeabilizantes',
    description: 'Vedacit, Bianco, selantes PU 40, Fixa Tudo, silicones, espumas e colas.',
    iconName: 'Droplets',
    color: 'from-blue-700 to-indigo-950',
    image: '/images/departamentos/quimicos-e-adesivos.webp',
  },
  {
    id: 'pintura',
    slug: 'pintura',
    name: 'Pintura e Acessórios',
    navName: 'Pintura',
    description: 'Tintas látex, tintas spray, solventes, thinners, trinchas, rolos e fitas.',
    iconName: 'Paintbrush',
    color: 'from-rose-600 to-red-950',
    image: '/images/departamentos/pintura.webp',
  },
  {
    id: 'hidraulica',
    slug: 'hidraulica',
    name: 'Tubos e Conexões',
    navName: 'Hidráulica',
    description: 'Tubos e conexões soldáveis, registros, caixas Sabesp, sifões e ralos.',
    iconName: 'Droplets',
    color: 'from-sky-600 to-blue-900',
    image: '/images/departamentos/hidraulica.webp',
  },
  {
    id: 'eletrica',
    slug: 'eletrica',
    name: 'Elétrica e Iluminação',
    navName: 'Elétrica',
    description: 'Fios e cabos flexíveis, tomadas, interruptores, módulos e lâmpadas LED.',
    iconName: 'Zap',
    color: 'from-amber-500 to-orange-900',
    image: '/images/departamentos/eletrica.webp',
  },
  {
    id: 'banheiro-e-cozinha',
    slug: 'banheiro-e-cozinha',
    name: 'Banheiro e Cozinha',
    navName: 'Banheiro e Cozinha',
    description: 'Bacias sanitárias, assentos, gabinetes, pias de granito, torneiras e chuveiros.',
    iconName: 'Sparkles',
    color: 'from-emerald-700 to-teal-950',
    image: '/images/departamentos/banheiro-e-cozinha.webp',
  },
  {
    id: 'ferramentas',
    slug: 'ferramentas',
    name: 'Ferramentas e Equipamentos',
    navName: 'Ferramentas e EPI',
    description: 'Pás, carriolas, trenas, discos de corte, chaves combinadas e aplicadores.',
    iconName: 'Hammer',
    color: 'from-orange-600 to-slate-900',
    image: '/images/departamentos/ferramentas.webp',
  },
  {
    id: 'ferragens',
    slug: 'ferragens',
    name: 'Ferragens e Segurança',
    navName: 'Ferragens',
    description: 'Fechaduras, dobradiças, pregos com cabeça, mãos francesas e parafusos.',
    iconName: 'Wrench',
    color: 'from-zinc-700 to-neutral-950',
    image: '/images/departamentos/ferragens.webp',
  },
  {
    id: 'jardim-e-utilidades',
    slug: 'jardim-e-utilidades',
    name: 'Jardim e Área Externa',
    navName: 'Jardim e Área Externa',
    description: 'Mangueiras de jardim trançadas, esguichos, desengripantes e lubrificantes.',
    iconName: 'Wrench',
    color: 'from-green-600 to-emerald-950',
    image: '/images/departamentos/jardim-e-utilidades.webp',
  },
];
